### ISSUE TITLE
htmlAfterThumbnail not working

### ISSUE THREAD

**Issue by gottenwit** [Sitronik/vue3-picture-swipe#2]
Hi! sitronik
I want to add button or any html then not work. 
htmlAfterThumbnail render commentcode 

![image](https://user-images.githubusercontent.com/52517915/147332962-22a78c51-f299-498a-9734-78ad6d2e821f.png)

![image](https://user-images.githubusercontent.com/52517915/147332651-77a7a03a-41c3-434b-8d03-1574e8b537c7.png)

Thank you so much.

**Comment by Sitronik** [comment]
Hi @gottenwit 
You need to check runtimeCompiler enabled in vue config:
```
runtimeCompiler: true
```

**Comment by gottenwit** [comment]
> Hi @gottenwit You need to check runtimeCompiler enabled in vue config:
> 
> ```
> runtimeCompiler: true
> ```

Thank you so much. This work perfectly,

**Comment by Sitronik** [comment]
> > Hi @gottenwit You need to check runtimeCompiler enabled in vue config:
> > ```
> > runtimeCompiler: true
> > ```
> 
> Thank you so much. This work perfectly,

You are welcome 😉
